### ISSUE TITLE
Webview support?

### ISSUE THREAD

**Issue by TheFocusDevHUN** [gen2brain/iup-go#19]
I read in the IUP docs that there is a [WebBrowser](https://www.tecgraf.puc-rio.br/iup/en/ctrl/iupweb.html) control, but it states that it's Linux and Windows only.
Is it possible to implement a control that is able to embed something like [this](https://github.com/webview/webview)?

**Comment by gen2brain** [comment]
There will not be support for any additional controls (Plot, Scintilla, WebBrowser, etc.), the reasonings are in https://github.com/gen2brain/iup-go/issues/5.

Basically, with only C core included, one can build on any platform with GTK+ or even Motif with plain `go build`. With additional controls that have C++ dependencies, I would probably have to build libs for all platforms or you lose the ease of use and create a painful-to-use library that no one will want/know how to use.

I would like only to add `Cells` and `Matrix` controls because something like ListView/TableView in the core is still on their TODO list, but that also requires the `CD` library, I will try to include it together with the core if possible when I find the time.

**Comment by gen2brain** [comment]
Btw. to embed something like `webview`, you must do it in the IUP, then here. These are just bindings.

**Comment by TheFocusDevHUN** [comment]
Ok, understandable. Thank you regardless!

**Comment by TheFocusDevHUN** [comment]
Hi there @gen2brain ! Thank you for implementing this feature! Although I haven't used this library for a while, I started a new cross platform project so about time to return to using it. Sure, I will test the web integrations. Oh and a slightly unrelated question. Is there a way to display a list with columns? Something like a file list in archiving programs (as I'm building one)

**Comment by gen2brain** [comment]
Hi, no, that would be a long-planned `Table` control that will utilize the native table controls available on all platforms and toolkits. When I finish everything I planned, I will maybe start working on the new Table control.  Depending on how many columns you need and for what purpose, you may want to consider using the regular list with images and maybe some separators. For example, I used one column with content separators. The original IUP has the `IupMatrix` control, but that requires additional libraries that I will not add here.

**Comment by TheFocusDevHUN** [comment]
I need a fairly simple table. You know, for displaying filenames and some usual info about them in the other few columns.
